Add ebs__enum_snapshots_unauth Module for Unauthenticated EBS Snapshot Reconnaissance
RhinoSecurityLabs/pacu pull request #370
Opened 2023-09-25 19:36 UTC by Y4nush

This pull request introduces a new module, ebs__enum_snapshots_unauth, designed for unauthenticated reconnaissance of public EBS snapshots. The module offers users the capability to search for snapshots based on account-id, keyword, list of account-ids, or a list of keywords. The purpose of this feature is to uncover snapshots related to a specific organization, thereby aiding in further reconnaissance.

Two main approaches are supported by this module:

1. Account ID Enumeration: This approach is useful when an organization's account ID is disclosed. It allows for the enumeration of snapshots related to the organization.
2. Keyword Enumeration: This method is employed to find snapshots related to an organization through the search of related keywords, aiming to disclose the organization's account ID.

This module was inspired by the article [Assume the Worst: AWS Assume Role Enumeration](https://rhinosecuritylabs.com/aws/assume-worst-aws-assume-role-enumeration/), and it aims to complement the existing ebs__enum_volumes_snapshots module, which appears to be more intended for authenticated enumeration.

Thank you for considering this addition. Looking forward to any feedback or suggestions for improvement.

2023-10-11 15:36 UTC, DaveYesland commented
Hi, thanks for the pull request. 
This module looks like a great idea. Sorry for the delay but we will review this as soon as possible! appreciate the contribution!

2023-10-26 16:11 UTC, DaveYesland requested changes
Just a couple formatting changes and I can get this merged. Let me know if you have an questions.

2023-10-26 16:11 UTC, DaveYesland commented on pacu/modules/ebs__enum_snapshots_unauth/main.py
> +        print('[ebs__enum_snapshots_unauth] Starting region {}...'.format(region))
remove the preceding "[ebs__enum_snapshots_unauth] " this is already handled by Pacu print()

2023-10-26 16:11 UTC, DaveYesland commented on pacu/modules/ebs__enum_snapshots_unauth/main.py
> +                print('[+] Snapshot found: {}'.format(snapshot['SnapshotId']))
remove the preceding "[+] " Pacu's print already has a formatted print()

2023-10-26 16:22 UTC, Y4nush commented
Hi Dave, thanks for your review. I have fixed the issues.

2023-10-26 21:59 UTC, DaveYesland approved these changes

2023-10-26 22:00 UTC, merged